export const brand = {
  name: "Doclira",
  product: "Doclira PDF",
  platform: "Windows 10 / 11 (64-bit)",
  price: "$29",
  purchaseUrl: "https://taixianglumark.gumroad.com/l/doclira-pdf",
  aiCreditsUrl: "https://doclira.com/buy/#ai-credits",
  installerUrl: "/downloads/DocliraPDF_Setup_v1.0.0_Windows_x64_EN.exe",
  liteUrl: "https://github.com/lienowen/doclira-pdf-lite",
  supportEmail: "lienowen@outlook.com",
  pricing: [
    {
      name: "Pro",
      price: "$29",
      audience: "For solo users and everyday PDF work",
      ai: "50 included AI credits",
      features: ["Batch watermark", "PDF to Word", "Compress, merge and split", "Light text correction"],
    },
    {
      name: "Business",
      price: "$59",
      audience: "For frequent document handling",
      ai: "200 included AI credits",
      features: ["Higher AI allowance", "Batch processing workflow", "Commercial document use", "Priority setup help"],
      highlight: true,
    },
    {
      name: "Enterprise",
      price: "$99",
      audience: "For teams and heavier use",
      ai: "500 included AI credits",
      features: ["Largest AI allowance", "Team-friendly license", "Bulk document workflow", "Upgrade support"],
    },
  ],
};
